name: Tag and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name (e.g., v2.0.0)"
        required: true

permissions:
  contents: write  # needed to push tags

jobs:
  create-tag:
    environment: releaseNewActionVersion  # 👈 this grants bypass permission
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create and push tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}
