name: Release GitHub Actions

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release"
        required: true
      working_directory:
        description: "Working directories to run commands in (comma-separated, optional)"
        required: false
        default: "setup-pandoc, setup-manifest, pr-push, check-r-package, pr-fetch"

permissions:
  contents: read

jobs:
  release:
    permissions:
      actions: read
      id-token: write
      contents: write

    uses: step-security/reusable-workflows/.github/workflows/actions_release.yaml@fix_Use-Audit-Fix-With-Mentioned-Directory
    with:
      tag: ${{ github.event.inputs.tag }}
      working_directory: ${{ github.event.inputs.working_directory }}
