name: action-markdownlint

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
permissions:
  contents: read
jobs:
  call-markdown-lint:
    uses: step-security/workflow-playground/.github/workflows/action-markdown-lint.yml@2d61f104b186b3a4299da1cab2144ff662842898
    with:
      action-tag: ${{ github.head_ref || github.ref_name }}

