name: Release GitHub Actions

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release"
        required: true
      script:
        description: "Specify the build script to run"
        required: true
        type: string
        default: "yarn run build"

permissions:
  contents: read

jobs:
  # This is the environment-protected gatekeeper job
  enforce-environment:
    runs-on: ubuntu-latest
    environment: releaseNewActionVersion
    steps:
      - name: Wait for environment approval
        run: echo "Environment check passed."

  # This is your actual release job
  release:
    needs: enforce-environment
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: step-security/reusable-workflows/.github/workflows/actions_release.yaml@v1
    with:
      tag: "${{ github.event.inputs.tag }}"
      script: "${{ github.event.inputs.script }}"