name: Check Maintained Action Scores

on:
  schedule:
    - cron: "0 0 * * *" # daily at midnight UTC
  workflow_dispatch:

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  score-check:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: "20"

      - name: Fetch scores and write results
        run: |
          cat << 'EOF' > check-scores.js
          const fs = require('fs');
          const path = require('path');
          const https = require('https');
          function fetchActionDetails(name) {
            const postData = JSON.stringify({ name });
            const options = {
              hostname: 'agent.api.stepsecurity.io',
              path: '/v1/github/actions/action-details',
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'Content-Length': Buffer.byteLength(postData),
                'x-beta': '1'
              }
            };
            return new Promise((resolve, reject) => {
              const req = https.request(options, res => {
                let data = '';
                res.on('data', chunk => data += chunk);
                res.on('end', () => {
                  try {
                    const json = JSON.parse(data);
                    resolve(json);
                  } catch (err) {
                    reject(new Error(`Invalid JSON for ${name}: ${err.message}`));
                  }
                });
              });
              req.on('error', reject);
              req.write(postData);
              req.end();
            });
          }
          async function main() {
            const filePath = path.join('src', 'lib', 'fixtures', 'app-values.ts');
            const content = fs.readFileSync(filePath, 'utf8');
            const match = content.match(/export const MAINTAINED_ACTIONS\s*=\s*(\[[\s\S]*?\])\s*as const;/);
            if (!match) {
              console.error('❌ Could not extract MAINTAINED_ACTIONS from app-values.ts');
              process.exit(1);
            }
            const actions = eval(match[1]); // Trusted input
            const lowScoreActions = [];
            const vulnerableActions = [];

            for (const action of actions) {
              const name = action.name;
              try {
                const result = await fetchActionDetails(name);
                const score = result.score?.score ?? 0;
                const vulnScore = result.score?.["vulnerabilities-score"] ?? 10;

                if (score < 10) {
                  lowScoreActions.push({ name, score });
                }

                if (vulnScore < 10) {
                  vulnerableActions.push({ name, vulnScore });
                }

              } catch (err) {
                console.error(`❌ Error fetching details for ${name}: ${err.message}`);
                process.exit(1);
              }
            }
            fs.writeFileSync('low-score-actions.json', JSON.stringify(lowScoreActions, null, 2));
            fs.writeFileSync('vulnerable-actions.json', JSON.stringify(vulnerableActions, null, 2));
          }
          main();
          EOF
          node check-scores.js
      - name: Print and fail if any scores < 10
        run: |
          if [ -f low-score-actions.json ]; then
            count=$(jq 'length' low-score-actions.json)
            if [ "$count" -gt 0 ]; then
              echo "❌ The following maintained actions have score < 10:"
              jq -r '.[] | "- \(.name): \(.score) → https://app.stepsecurity.io/action-advisor/\(.name)"' low-score-actions.json
              exit 1
            else
              echo "✅ All maintained actions have score >= 10"
            fi
          else
            echo "ℹ️ low-score-actions.json not found — assuming no actions evaluated."
          fi

      - name: Print and fail if any vulnerabilities detected
        run: |
          if [ -f vulnerable-actions.json ]; then
            count=$(jq 'length' vulnerable-actions.json)
            if [ "$count" -gt 0 ]; then
              echo "🚨 Maintained actions with vulnerabilities (vulnerabilities-score < 10):"
              jq -r '.[] | "- \(.name): vulnerabilities-score = \(.vulnScore)\n  → Advisor: https://app.stepsecurity.io/action-advisor/\(.name)\n  → GitHub Security: https://github.com/\(.name)/security/code-scanning"' vulnerable-actions.json

              echo ""
              exit 1
            else
              echo "✅ No vulnerabilities found in maintained actions"
            fi
          else
            echo "ℹ️ vulnerable-actions.json not found — assuming no actions evaluated."
          fi
