name: "Build"
on:
  [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
      with:
        egress-policy: audit
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: |
        npm i
        npm run all
    - name: Upload coverage reports to Codecov
      if: always()
      uses: codecov/codecov-action@v3
