name: Test Tag Protection With Default Token

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create-tag-protection:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # doesn't help here, but you can try
      actions: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Try to create tag protection rule with GITHUB_TOKEN
        run: |
          curl -i -X POST "https://api.github.com/repos/${{ github.repository }}/tags/protection" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -d '{"pattern": "v*"}'
